### ISSUE TITLE
eval Usage

### ISSUE THREAD

**Issue by ZackaryH8** [Zuiron/altv_lisa_opensource#4]
You shouldn't be using eval ([src](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#:~:text=eval()%20is%20a%20function,eval()%20evaluates%20the%20statements.)) consider adding a warning to readme or archiving this repository.

>eval() is a dangerous function, which executes the code it's passed with the privileges of the caller. If you run eval() with a string that could be affected by a malicious party, you may end up running malicious code on the user's machine with the permissions of your webpage / extension. More importantly, a third-party code can see the scope in which eval() was invoked, which can lead to possible attacks in ways to which the similar Function is not susceptible.

**Comment by dexslab** [comment]
YA foo why you usin all them evals SECURITY RISK!!!!

**Comment by Zuiron** [comment]
> I offer zero support for this, you need some programming knowledge.
please note this is OLD and outdated
