### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by plusman1560mami** [Zuiron/altv_lisa_opensource#5]
It has been 1 month, I haven't found for fixed :)))
The mouse is not visible at the entrance
I want to do a job for a fee
can you help me ?
my discord  LeO#4846
write me pls <3

https://media.discordapp.net/attachments/750807105543602240/750809457717674035/unknown.png?width=967&height=500

**Comment by assadi-dev** [comment]
Change setFocusArea to  setFocusPosAndVel in line 192 of lisa_login/client/startup.mjs
